'use client'

import { useState } from 'react'
import {
  Activity, AlertCircle, ArrowLeft, ArrowUpRight, Bell, BookOpen, Check,
  ChevronRight, CircleHelp, ClipboardCheck, FileClock, Fingerprint, HeartPulse,
  LayoutDashboard, LockKeyhole, Menu, MessageCircle, MoreHorizontal, Plus,
  Search, ShieldCheck, Sparkles, Users, X,
} from 'lucide-react'

const cases = [
  { id: 'WF-2408', name: 'R. Kumar', unit: '41st Battalion · North Sector', signal: '3 consecutive check-ins missed', risk: 'Elevated', status: 'Open', time: '12 min ago', initials: 'RK', tone: 'amber' },
  { id: 'WF-2405', name: 'A. Singh', unit: '12th Battalion · Central Sector', signal: 'Peer concern reported', risk: 'Priority', status: 'Open', time: '2 hrs ago', initials: 'AS', tone: 'rose' },
  { id: 'WF-2398', name: 'M. Das', unit: '8th Battalion · East Sector', signal: 'Wellness score changed', risk: 'Monitor', status: 'Follow-up', time: 'Yesterday', initials: 'MD', tone: 'slate' },
  { id: 'WF-2392', name: 'S. Yadav', unit: '19th Battalion · West Sector', signal: 'Follow-up due', risk: 'Monitor', status: 'Follow-up', time: '2 days ago', initials: 'SY', tone: 'green' },
  { id: 'WF-2387', name: 'N. Thomas', unit: '7th Battalion · North Sector', signal: 'Self-referral', risk: 'Priority', status: 'Open', time: '3 days ago', initials: 'NT', tone: 'rose' },
]

type View = 'Overview' | 'Cases' | 'Interventions' | 'Team pulse' | 'Audit ledger' | 'Guidance'

const navItems: { label: View; icon: typeof LayoutDashboard; count?: string }[] = [
  { label: 'Overview', icon: LayoutDashboard }, { label: 'Cases', icon: HeartPulse, count: '08' },
  { label: 'Interventions', icon: MessageCircle }, { label: 'Team pulse', icon: Activity },
]

export function SahayakApp() {
  const [view, setView] = useState<View>('Overview')
  const [selected, setSelected] = useState(0)
  const [mobileMenu, setMobileMenu] = useState(false)
  const [breakGlass, setBreakGlass] = useState(false)
  const [intervened, setIntervened] = useState(false)

  const go = (next: View) => { setView(next); setMobileMenu(false) }
  const openCase = (index: number) => { setSelected(index); setView('Case Detail' as View) }
  const current = cases[selected]

  return <main className="min-h-screen bg-[#f5f7f6] text-[#15221f]">
    <div className="flex min-h-screen">
      <Sidebar view={view} go={go} />
      <section className="min-w-0 flex-1">
        <Header view={view} mobileMenu={mobileMenu} setMobileMenu={setMobileMenu} go={go} />
        <div className="mx-auto max-w-[1420px] px-5 py-7 sm:px-8 lg:px-10 lg:py-9">
          {view === 'Overview' && <Overview go={go} openCase={openCase} current={current} setIntervened={setIntervened} />}
          {view === 'Cases' && <CasesView openCase={openCase} />}
          {view === 'Case Detail' && <Detail current={current} go={go} breakGlass={breakGlass} setBreakGlass={setBreakGlass} intervened={intervened} setIntervened={setIntervened} />}
          {view === 'Interventions' && <Interventions />}
          {view === 'Team pulse' && <TeamPulse />}
          {view === 'Audit ledger' && <AuditLedger />}
          {view === 'Guidance' && <Guidance />}
        </div>
      </section>
    </div>
    {breakGlass && <BreakGlass close={() => setBreakGlass(false)} />}
  </main>
}

function Sidebar({ view, go }: { view: View; go: (view: View) => void }) {
  return <aside className="hidden w-[248px] shrink-0 flex-col border-r border-[#dfe7e3] bg-[#fbfcfb] px-5 py-6 lg:flex">
    <div className="mb-11 flex items-center gap-3 px-2"><div className="flex size-9 items-center justify-center rounded-xl bg-[#123e39] text-[#d5f1dc]"><ShieldCheck size={19} /></div><div><div className="font-serif text-[19px] font-semibold tracking-tight">SAHAYAK</div><div className="text-[9px] font-semibold uppercase tracking-[0.19em] text-[#78908a]">Welfare command</div></div></div>
    <NavGroup title="Workspace">{navItems.map(({ label, icon: Icon, count }) => <NavButton key={label} active={view === label} onClick={() => go(label)}><Icon size={17} strokeWidth={1.8} />{label}{count && <span className="ml-auto rounded-md bg-[#d1e7da] px-1.5 py-0.5 text-[10px] font-bold text-[#27705c]">{count}</span>}</NavButton>)}</NavGroup>
    <NavGroup title="Governance"><NavButton active={view === 'Audit ledger'} onClick={() => go('Audit ledger')}><FileClock size={17} strokeWidth={1.8} />Audit ledger</NavButton><NavButton active={view === 'Guidance'} onClick={() => go('Guidance')}><BookOpen size={17} strokeWidth={1.8} />Guidance</NavButton></NavGroup>
    <div className="mt-auto rounded-2xl border border-[#dfe9e3] bg-[#f1f7f3] p-4"><div className="mb-3 flex size-8 items-center justify-center rounded-lg bg-white text-[#28725e]"><CircleHelp size={16} /></div><div className="text-[12px] font-semibold text-[#27544b]">Need a second view?</div><p className="mt-1 text-[11px] leading-relaxed text-[#708780]">Review escalation guidance before your next conversation.</p><button onClick={() => go('Guidance')} className="mt-3 text-[11px] font-bold text-[#27705c]">Open guidance <ArrowUpRight className="ml-1 inline" size={12} /></button></div>
  </aside>
}

function NavGroup({ title, children }: { title: string; children: React.ReactNode }) { return <div className="mb-8"><div className="mb-3 px-2 text-[10px] font-bold uppercase tracking-[0.16em] text-[#8ba099]">{title}</div><nav className="flex flex-col gap-1">{children}</nav></div> }
function NavButton({ active, onClick, children }: { active: boolean; onClick: () => void; children: React.ReactNode }) { return <button onClick={onClick} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-left text-[13px] font-medium transition-colors ${active ? 'bg-[#e6f1eb] text-[#174d43]' : 'text-[#6c7d78] hover:bg-[#f0f5f2]'}`}>{children}</button> }

function Header({ view, mobileMenu, setMobileMenu, go }: { view: View; mobileMenu: boolean; setMobileMenu: (value: boolean) => void; go: (view: View) => void }) { return <header className="flex h-[74px] items-center justify-between border-b border-[#e3eae7] bg-[#fbfcfb] px-5 sm:px-8 lg:px-10"><div className="flex items-center gap-3"><button onClick={() => setMobileMenu(!mobileMenu)} className="rounded-lg p-2 text-[#60746e] lg:hidden"><Menu size={20} /></button><div className="lg:hidden"><span className="font-serif text-lg font-semibold">SAHAYAK</span></div><div className="hidden items-center gap-2 text-[12px] text-[#879791] sm:flex"><span>Welfare command</span><ChevronRight size={13} /><span className="font-medium text-[#304640]">{view}</span></div></div><div className="flex items-center gap-3"><button className="hidden rounded-lg border border-[#e0e8e4] bg-white px-3 py-2 text-[11px] font-semibold text-[#49635b] sm:flex sm:items-center sm:gap-2"><Search size={14} /> Search</button><button className="relative rounded-lg p-2 text-[#6c7d78]"><Bell size={18} strokeWidth={1.8} /><span className="absolute right-1.5 top-1.5 size-1.5 rounded-full bg-[#d47a58]" /></button><div className="flex items-center gap-2 border-l border-[#e2e9e6] pl-3"><div className="flex size-8 items-center justify-center rounded-full bg-[#d5e9df] text-[11px] font-bold text-[#28604e]">PS</div><div className="hidden text-left sm:block"><div className="text-[11px] font-semibold">Priya Shah</div><div className="text-[10px] text-[#8a9994]">Welfare officer</div></div></div></div>{mobileMenu && <div className="absolute left-4 right-4 top-[66px] z-20 rounded-2xl border border-[#dfe8e3] bg-white p-3 shadow-xl lg:hidden">{navItems.map(({ label, icon: Icon }) => <button key={label} onClick={() => go(label)} className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm text-[#426056] hover:bg-[#f0f5f2]"><Icon size={16} />{label}</button>)}</div>}</header> }

function PageIntro({ eyebrow, title, description, action }: { eyebrow?: string; title: string; description: string; action?: React.ReactNode }) { return <div className="mb-8 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div>{eyebrow && <div className="mb-2 flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[0.15em] text-[#6c8d82]"><span className="size-1.5 rounded-full bg-[#4e9a77]" />{eyebrow}</div>}<h1 className="font-serif text-[34px] leading-tight tracking-[-0.03em] text-[#18342e] sm:text-[41px]">{title}</h1><p className="mt-2 text-[13px] text-[#75857f]">{description}</p></div>{action}</div> }

function Overview({ go, openCase, current, setIntervened }: { go: (view: View) => void; openCase: (index: number) => void; current: typeof cases[0]; setIntervened: (v: boolean) => void }) { return <><PageIntro eyebrow="Tuesday, 20 August 2024" title="Good morning, Priya." description="There are a few people who could use a closer look today." action={<div className="flex gap-2"><button className="flex items-center gap-2 rounded-xl border border-[#dce6e0] bg-white px-3.5 py-2.5 text-[12px] font-semibold text-[#557068]"><ClipboardCheck size={15} /> My notes</button><button onClick={() => setIntervened(true)} className="flex items-center gap-2 rounded-xl bg-[#174c42] px-3.5 py-2.5 text-[12px] font-semibold text-white"><Plus size={15} /> Log intervention</button></div>} /><div className="mb-8 grid grid-cols-2 gap-3 md:grid-cols-4"><Stat label="Open cases" value="08" detail="2 new today" accent="text-[#bc684f]" /><Stat label="Follow-ups due" value="04" detail="Next due in 2 days" accent="text-[#397c68]" /><Stat label="Avg. response" value="18m" detail="↓ 12% this month" accent="text-[#397c68]" /><Stat label="Team check-in" value="86%" detail="Within expected range" accent="text-[#397c68]" /></div><div className="mb-3 flex items-center justify-between"><div><h2 className="font-serif text-[21px] font-semibold text-[#1c3b33]">Cases needing attention</h2><p className="mt-1 text-[12px] text-[#83918d]">Prioritised by recency and welfare relevance</p></div><button onClick={() => go('Cases')} className="text-[11px] font-bold text-[#327460]">View all cases <ArrowUpRight className="ml-1 inline" size={12} /></button></div><div className="grid gap-5 xl:grid-cols-[minmax(0,0.98fr)_minmax(480px,1.28fr)]"><Queue openCase={openCase} /><DetailCard current={current} onIntervene={() => setIntervened(true)} /></div></> }

function Queue({ openCase }: { openCase: (index: number) => void }) { return <div className="overflow-hidden rounded-2xl border border-[#dfe8e3] bg-white shadow-[0_8px_30px_rgba(30,72,58,0.035)]"><div className="border-b border-[#edf1ef] px-5 py-4 text-[11px] font-bold uppercase tracking-[0.13em] text-[#80918b]">Priority queue</div><div className="divide-y divide-[#edf1ef]">{cases.slice(0, 3).map((item, index) => <CaseRow key={item.id} item={item} onClick={() => openCase(index)} />)}</div><button onClick={() => openCase(0)} className="flex w-full items-center justify-center gap-1 border-t border-[#edf1ef] py-3 text-[11px] font-bold text-[#46816e]">Open case list <ArrowUpRight size={12} /></button></div> }
function CaseRow({ item, onClick }: { item: typeof cases[0]; onClick: () => void }) { return <button onClick={onClick} className="flex w-full gap-3 px-5 py-4 text-left transition-colors hover:bg-[#f8fbf9]"><Avatar item={item} /><div className="min-w-0 flex-1"><div className="flex items-baseline justify-between gap-2"><span className="truncate text-[13px] font-semibold text-[#2d453e]">{item.name}</span><span className="shrink-0 text-[10px] text-[#9aa6a1]">{item.time}</span></div><div className="mt-0.5 truncate text-[11px] text-[#899791]">{item.unit}</div><div className="mt-2 flex items-center gap-2"><Risk value={item.risk} /><span className="truncate text-[10px] text-[#788a84]">{item.signal}</span></div></div><ChevronRight className="mt-2 shrink-0 text-[#bdc9c4]" size={16} /></button> }
function Avatar({ item }: { item: typeof cases[0] }) { return <div className={`flex size-9 shrink-0 items-center justify-center rounded-full text-[11px] font-bold ${item.tone === 'rose' ? 'bg-[#f7e4de] text-[#a55f4d]' : item.tone === 'amber' ? 'bg-[#f5ead2] text-[#9b7132]' : 'bg-[#e3ebec] text-[#60747a]'}`}>{item.initials}</div> }
function Risk({ value }: { value: string }) { return <span className={`rounded-full px-2 py-0.5 text-[10px] font-semibold ${value === 'Priority' ? 'bg-[#fae6e0] text-[#a55342]' : value === 'Elevated' ? 'bg-[#f7ecd5] text-[#9b7132]' : 'bg-[#e8eff0] text-[#5d7379]'}`}>{value}</span> }

function DetailCard({ current, onIntervene }: { current: typeof cases[0]; onIntervene: () => void }) { return <div className="rounded-2xl border border-[#dfe8e3] bg-white shadow-[0_8px_30px_rgba(30,72,58,0.035)]"><div className="flex items-start justify-between border-b border-[#edf1ef] px-5 py-5 sm:px-6"><div className="flex gap-3"><Avatar item={current} /><div><div className="flex items-center gap-2"><h2 className="text-[16px] font-semibold text-[#25443b]">{current.name}</h2><Risk value={current.risk} /></div><div className="mt-1 text-[11px] text-[#899791]">{current.id} · {current.unit}</div></div></div><MoreHorizontal size={19} className="text-[#8d9b96]" /></div><div className="p-5 sm:p-6"><div className="mb-5 flex items-center gap-2 text-[11px] font-bold uppercase tracking-[0.13em] text-[#9a6d35]"><Sparkles size={15} />Why this was flagged</div><div className="rounded-xl border border-[#f0e5ce] bg-[#fffaf0] p-4"><div className="flex gap-3"><AlertCircle className="mt-0.5 shrink-0 text-[#bf8141]" size={17} /><div><div className="text-[13px] font-semibold text-[#60472d]">{current.signal}</div><p className="mt-1 text-[11px] leading-relaxed text-[#8a7155]">This is a change from their recent pattern. It may be useful to check in privately and understand what has changed.</p></div></div></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><Signal label="Check-in pattern" value="Changed" tone="amber" /><Signal label="Last contact" value="14 Aug 2024" tone="slate" /><Signal label="Peer context" value="No concern" tone="green" /></div><div className="mt-6 flex flex-wrap gap-2 border-t border-[#edf1ef] pt-5"><button onClick={onIntervene} className="rounded-lg bg-[#174c42] px-3.5 py-2.5 text-[11px] font-bold text-white">Start intervention</button><button className="rounded-lg border border-[#dce6e0] px-3.5 py-2.5 text-[11px] font-bold text-[#557068]">Recommended next step</button></div></div></div> }

function CasesView({ openCase }: { openCase: (index: number) => void }) { const [query, setQuery] = useState(''); const filtered = cases.filter((item) => `${item.name} ${item.id} ${item.unit} ${item.signal}`.toLowerCase().includes(query.toLowerCase())); return <><PageIntro title="Cases" description="A complete queue of welfare cases requiring care and follow-up." action={<button className="flex items-center gap-2 rounded-xl bg-[#174c42] px-3.5 py-2.5 text-[12px] font-semibold text-white"><Plus size={15} /> New case</button>} /><div className="rounded-2xl border border-[#dfe8e3] bg-white shadow-[0_8px_30px_rgba(30,72,58,0.035)]"><div className="flex flex-col gap-3 border-b border-[#edf1ef] p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-2 text-[11px] font-bold uppercase tracking-[0.13em] text-[#80918b]">All cases <span className="rounded-md bg-[#eaf3ed] px-1.5 py-0.5 text-[#397c68]">08</span></div><div className="flex items-center gap-2 rounded-lg border border-[#e0e8e4] px-3 py-2"><Search size={14} className="text-[#95a39d]" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search cases..." className="w-full bg-transparent text-[12px] outline-none placeholder:text-[#a2afa9]" /></div></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead className="bg-[#f8fbf9] text-[10px] uppercase tracking-[0.12em] text-[#8a9a94]"><tr><th className="px-5 py-3 font-bold">Case / person</th><th className="px-5 py-3 font-bold">Unit</th><th className="px-5 py-3 font-bold">Severity</th><th className="px-5 py-3 font-bold">Welfare signal</th><th className="px-5 py-3 font-bold">Status</th><th className="px-5 py-3 font-bold">Time</th></tr></thead><tbody className="divide-y divide-[#edf1ef]">{filtered.map((item, index) => <tr key={item.id} onClick={() => openCase(cases.indexOf(item))} className="cursor-pointer hover:bg-[#f8fbf9]"><td className="px-5 py-4"><div className="flex items-center gap-3"><Avatar item={item} /><div><div className="text-[13px] font-semibold text-[#2d453e]">{item.name}</div><div className="text-[10px] text-[#99a6a0]">{item.id}</div></div></div></td><td className="px-5 py-4 text-[11px] text-[#70827b]">{item.unit}</td><td className="px-5 py-4"><Risk value={item.risk} /></td><td className="px-5 py-4 text-[11px] text-[#70827b]">{item.signal}</td><td className="px-5 py-4 text-[11px] font-semibold text-[#397c68]">{item.status}</td><td className="px-5 py-4 text-[11px] text-[#99a6a0]">{item.time}</td></tr>)}</tbody></table></div></div></> }

function Detail({ current, go, setBreakGlass, intervened, setIntervened }: { current: typeof cases[0]; go: (view: View) => void; breakGlass: boolean; setBreakGlass: (v: boolean) => void; intervened: boolean; setIntervened: (v: boolean) => void }) { return <><button onClick={() => go('Cases')} className="mb-5 flex items-center gap-2 text-[11px] font-bold text-[#46816e]"><ArrowLeft size={14} /> Back to cases</button><PageIntro title={`${current.name} · ${current.id}`} description={`${current.unit} · Dedicated case view`} action={<div className="flex gap-2"><button onClick={() => setBreakGlass(true)} className="flex items-center gap-2 rounded-xl border border-[#dce6e0] bg-white px-3.5 py-2.5 text-[12px] font-semibold text-[#557068]"><Fingerprint size={15} /> Request identity access</button><button onClick={() => setIntervened(true)} className="flex items-center gap-2 rounded-xl bg-[#174c42] px-3.5 py-2.5 text-[12px] font-semibold text-white"><MessageCircle size={15} /> Start intervention</button></div>} /><div className="grid gap-5 xl:grid-cols-[minmax(0,1.3fr)_minmax(320px,0.7fr)]"><DetailCard current={current} onIntervene={() => setIntervened(true)} /><div className="rounded-2xl border border-[#dfe8e3] bg-[#eaf5ef] p-5 sm:p-6"><div className="mb-5 flex items-center gap-2 text-[#286c58]"><Fingerprint size={18} /><span className="text-[11px] font-bold uppercase tracking-[0.13em]">Privacy & care</span></div><h3 className="font-serif text-[20px] leading-snug text-[#214c3f]">A person, not a profile.</h3><p className="mt-2 text-[12px] leading-relaxed text-[#668078]">Identity is protected unless access is necessary, authorised, and recorded.</p><div className="mt-5 flex items-center gap-2 border-t border-[#d2e8db] pt-4 text-[11px] font-semibold text-[#3d7764]"><LockKeyhole size={14} /> All access is audit logged</div></div></div><div className="mt-5 rounded-2xl border border-[#dfe8e3] bg-white p-5 sm:p-6"><div className="mb-5"><h2 className="font-serif text-[19px] font-semibold text-[#25443b]">Intervention history</h2><p className="mt-1 text-[11px] text-[#899791]">A clear record of support, not surveillance</p></div><HistoryItem date="Today, 09:42" title="Case reviewed" description="Welfare signal and recent context reviewed by Priya Shah." />{intervened && <HistoryItem date="Today, now" title="Intervention started" description="A support conversation has been logged for follow-up." />}<HistoryItem date="14 Aug 2024" title="Check-in completed" description="Routine wellness check-in recorded." /></div></> }

function Interventions() { return <><PageIntro title="Interventions" description="Support conversations, follow-ups, and care actions in one place." action={<button className="flex items-center gap-2 rounded-xl bg-[#174c42] px-3.5 py-2.5 text-[12px] font-semibold text-white"><Plus size={15} /> Log intervention</button>} /><div className="grid gap-4 md:grid-cols-3"><Stat label="This month" value="24" detail="Care actions recorded" accent="text-[#397c68]" /><Stat label="Follow-ups due" value="04" detail="Next due in 2 days" accent="text-[#bc684f]" /><Stat label="Completed" value="18" detail="75% completion rate" accent="text-[#397c68]" /></div><div className="mt-6 rounded-2xl border border-[#dfe8e3] bg-white p-5"><h2 className="mb-4 font-serif text-[21px] font-semibold text-[#1c3b33]">Recent intervention records</h2>{cases.slice(0, 4).map((item, i) => <div key={item.id} className="flex items-center justify-between border-t border-[#edf1ef] py-4"><div className="flex items-center gap-3"><Avatar item={item} /><div><div className="text-[13px] font-semibold text-[#2d453e]">{i % 2 ? 'Follow-up scheduled' : 'Support conversation logged'}</div><div className="mt-1 text-[11px] text-[#899791]">{item.name} · {item.unit}</div></div></div><span className="text-[10px] text-[#9aa6a1]">{item.time}</span></div>)}</div></> }

function TeamPulse() { return <><PageIntro title="Team pulse" description="Aggregate signals to help commanders care for teams without exposing individual identities." /><div className="grid gap-4 md:grid-cols-3"><Stat label="Check-in participation" value="86%" detail="Within expected range" accent="text-[#397c68]" /><Stat label="Teams in range" value="14 / 16" detail="2 need a closer look" accent="text-[#397c68]" /><Stat label="Trend" value="Stable" detail="Across the last 30 days" accent="text-[#397c68]" /></div><div className="mt-6 grid gap-5 lg:grid-cols-2"><PulseCard title="Wellbeing signal by sector" rows={['North Sector', 'Central Sector', 'East Sector', 'West Sector']} /><PulseCard title="Aggregate check-in rhythm" rows={['Routine participation', 'Peer support activity', 'Follow-up completion', 'Response confidence']} /></div></> }
function PulseCard({ title, rows }: { title: string; rows: string[] }) { return <div className="rounded-2xl border border-[#dfe8e3] bg-white p-5 sm:p-6"><h2 className="font-serif text-[20px] font-semibold text-[#25443b]">{title}</h2><div className="mt-5 flex flex-col gap-4">{rows.map((row, i) => <div key={row}><div className="mb-2 flex justify-between text-[11px]"><span className="text-[#61766d]">{row}</span><span className="font-semibold text-[#397c68]">{[86, 72, 91, 78][i]}%</span></div><div className="h-2 rounded-full bg-[#edf3ef]"><div className="h-2 rounded-full bg-[#79ad92]" style={{ width: `${[86, 72, 91, 78][i]}%` }} /></div></div>)}</div></div> }

function AuditLedger() { return <><PageIntro title="Audit ledger" description="A transparent record of sensitive access and governance actions." action={<button className="flex items-center gap-2 rounded-xl border border-[#dce6e0] bg-white px-3.5 py-2.5 text-[12px] font-semibold text-[#557068]"><FileClock size={15} /> Export ledger</button>} /><div className="rounded-2xl border border-[#dfe8e3] bg-white p-5 sm:p-6"><div className="mb-5 flex items-center gap-3"><div className="flex size-10 items-center justify-center rounded-xl bg-[#eaf5ef] text-[#286c58]"><ShieldCheck size={18} /></div><div><h2 className="font-serif text-[20px] font-semibold text-[#25443b]">Recent governance activity</h2><p className="text-[11px] text-[#899791]">Every identity access request is recorded here.</p></div></div>{['Case reviewed · WF-2408', 'Aggregate team pulse viewed', 'Identity access request submitted · WF-2405', 'Guidance article opened'].map((event, i) => <div key={event} className="flex items-center justify-between border-t border-[#edf1ef] py-4"><div className="flex items-center gap-3"><div className="size-2 rounded-full bg-[#6eaa8b]" /><span className="text-[12px] font-semibold text-[#3b554c]">{event}</span></div><span className="text-[10px] text-[#9aa6a1]">{i + 1}h ago · Priya Shah</span></div>)}</div></> }

function Guidance() { return <><PageIntro title="Guidance" description="Practical support for welfare conversations, escalation, and privacy." /><div className="grid gap-4 md:grid-cols-2"><Guide title="Starting a conversation" icon={MessageCircle} text="Use open, private questions. Let the person choose what they want to share and avoid assumptions." /><Guide title="When to escalate" icon={AlertCircle} text="Escalate when there is an immediate safety concern, repeated missed contact, or a change that needs specialist support." /><Guide title="Privacy by default" icon={LockKeyhole} text="Keep identities protected. Request access only when necessary to provide care, and always record the reason." /><Guide title="Follow-up rhythm" icon={ClipboardCheck} text="Agree on a next step together, set a clear follow-up date, and record the support action rather than surveillance detail." /></div></> }
function Guide({ title, icon: Icon, text }: { title: string; icon: typeof MessageCircle; text: string }) { return <div className="rounded-2xl border border-[#dfe8e3] bg-white p-5"><div className="mb-4 flex size-10 items-center justify-center rounded-xl bg-[#eaf5ef] text-[#286c58]"><Icon size={18} /></div><h2 className="font-serif text-[19px] font-semibold text-[#25443b]">{title}</h2><p className="mt-2 text-[12px] leading-relaxed text-[#70827b]">{text}</p><button className="mt-4 text-[11px] font-bold text-[#397c68]">Read guidance <ArrowUpRight className="ml-1 inline" size={12} /></button></div> }

function BreakGlass({ close }: { close: () => void }) { return <div className="fixed inset-0 z-30 flex items-center justify-center bg-[#14332d]/25 p-5" onClick={close}><div className="w-full max-w-[420px] rounded-2xl border border-[#dbe8e1] bg-white p-6 shadow-2xl" onClick={(e) => e.stopPropagation()}><div className="flex items-start justify-between"><div className="flex size-10 items-center justify-center rounded-xl bg-[#f5ead2] text-[#9b7132]"><LockKeyhole size={18} /></div><button onClick={close} className="text-[#9aa7a2]"><X size={18} /></button></div><h2 className="mt-4 font-serif text-[22px] font-semibold text-[#21453b]">Request identity access</h2><p className="mt-2 text-[12px] leading-relaxed text-[#6f8079]">Access is reserved for situations where identity is necessary to provide support. Your reason will be recorded in the audit ledger.</p><label className="mt-5 block text-[11px] font-bold text-[#587068]">Reason for access</label><textarea className="mt-2 h-24 w-full resize-none rounded-xl border border-[#dce6e0] bg-[#fbfdfb] p-3 text-[12px] outline-none focus:border-[#77a993]" placeholder="Briefly describe why access is needed..." /><div className="mt-4 flex justify-end gap-2"><button onClick={close} className="rounded-lg px-3.5 py-2.5 text-[11px] font-bold text-[#6f8079]">Cancel</button><button onClick={close} className="rounded-lg bg-[#174c42] px-3.5 py-2.5 text-[11px] font-bold text-white">Submit request</button></div></div></div> }

function Stat({ label, value, detail, accent }: { label: string; value: string; detail: string; accent: string }) { return <div className="rounded-2xl border border-[#dfe8e3] bg-white px-4 py-4 shadow-[0_8px_30px_rgba(30,72,58,0.025)] sm:px-5"><div className="text-[10px] font-bold uppercase tracking-[0.12em] text-[#8a9a94]">{label}</div><div className={`mt-2 font-serif text-[27px] font-semibold ${accent}`}>{value}</div><div className="mt-1 text-[10px] text-[#7f9089]">{detail}</div></div> }
function Signal({ label, value, tone }: { label: string; value: string; tone: string }) { return <div className="rounded-xl bg-[#f7faf8] p-3"><div className="text-[10px] text-[#91a19b]">{label}</div><div className={`mt-1 text-[12px] font-semibold ${tone === 'amber' ? 'text-[#a97532]' : tone === 'green' ? 'text-[#397c68]' : 'text-[#647773]'}`}>{value}</div></div> }
function HistoryItem({ date, title, description }: { date: string; title: string; description: string }) { return <div className="relative border-l border-[#dce8e1] pb-5 pl-6 last:pb-0"><span className="absolute -left-[6px] top-0.5 flex size-2.5 rounded-full border-2 border-white bg-[#6eaa8b] ring-1 ring-[#cfe2d8]" /><div className="text-[10px] font-semibold text-[#91a19b]">{date}</div><div className="mt-1 text-[12px] font-semibold text-[#3b554c]">{title}</div><div className="mt-1 text-[11px] leading-relaxed text-[#81918b]">{description}</div></div> }
